"""Initial schema

Revision ID: 01fd7e96e340
Revises: 
Create Date: 2026-09-06 18:14:20.750658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fd7e96e340'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('reorder_level', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_materials_material_code'), 'inventory_materials', ['material_code'], unique=True)
    op.create_table('production_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('line_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_line_code'), 'production_lines', ['line_code'], unique=True)
    op.create_table('production_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('total_makespan_hours', sa.Float(), nullable=False),
    sa.Column('optimizer_status', sa.String(length=50), nullable=False),
    sa.Column('schedule_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('standard_production_time', sa.Float(), nullable=False),
    sa.Column('required_materials', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('demand_forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_forecasts_forecast_date'), 'demand_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_demand_forecasts_product_id'), 'demand_forecasts', ['product_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['inventory_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_created_at'), 'inventory_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_material_id'), 'inventory_transactions', ['material_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('machine_name', sa.String(length=100), nullable=False),
    sa.Column('machine_type', sa.String(length=10), nullable=False),
    sa.Column('production_line', sa.String(length=50), nullable=False),
    sa.Column('production_line_id', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=True)
    op.create_table('production_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_order_code'), 'production_orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_production_orders_product_id'), 'production_orders', ['product_id'], unique=False)
    op.create_table('schedule_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changes_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['production_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_revisions_schedule_id'), 'schedule_revisions', ['schedule_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_machine_id'), 'alerts', ['machine_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('machine_health_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_health_history_machine_id'), 'machine_health_history', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_health_history_recorded_at'), 'machine_health_history', ['recorded_at'], unique=False)
    op.create_table('machine_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('machine_type', sa.String(length=10), nullable=False),
    sa.Column('air_temperature', sa.Float(), nullable=False),
    sa.Column('process_temperature', sa.Float(), nullable=False),
    sa.Column('rotational_speed', sa.Float(), nullable=False),
    sa.Column('torque', sa.Float(), nullable=False),
    sa.Column('tool_wear', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_readings_machine_id'), 'machine_readings', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_readings_timestamp'), 'machine_readings', ['timestamp'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('maintenance_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_machine_id'), 'maintenance_records', ['machine_id'], unique=False)
    op.create_table('production_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['production_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batches_batch_number'), 'production_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_production_batches_machine_id'), 'production_batches', ['machine_id'], unique=False)
    op.create_index(op.f('ix_production_batches_order_id'), 'production_batches', ['order_id'], unique=False)
    op.create_index(op.f('ix_production_batches_product_id'), 'production_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_production_batches_schedule_id'), 'production_batches', ['schedule_id'], unique=False)
    op.create_table('anomaly_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('reading_id', sa.String(length=36), nullable=True),
    sa.Column('anomaly_detected', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reading_id'], ['machine_readings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_predictions_machine_id'), 'anomaly_predictions', ['machine_id'], unique=False)
    op.create_index(op.f('ix_anomaly_predictions_timestamp'), 'anomaly_predictions', ['timestamp'], unique=False)
    op.create_table('machine_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('reading_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('failure_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reading_id'], ['machine_readings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_predictions_created_at'), 'machine_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_machine_predictions_machine_id'), 'machine_predictions', ['machine_id'], unique=False)
    op.create_table('quality_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('mixing_speed', sa.Float(), nullable=False),
    sa.Column('mixing_time', sa.Float(), nullable=False),
    sa.Column('process_features', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('pass_probability', sa.Float(), nullable=False),
    sa.Column('quality_risk', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_predictions_batch_id'), 'quality_predictions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_quality_predictions_created_at'), 'quality_predictions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_predictions_created_at'), table_name='quality_predictions')
    op.drop_index(op.f('ix_quality_predictions_batch_id'), table_name='quality_predictions')
    op.drop_table('quality_predictions')
    op.drop_index(op.f('ix_machine_predictions_machine_id'), table_name='machine_predictions')
    op.drop_index(op.f('ix_machine_predictions_created_at'), table_name='machine_predictions')
    op.drop_table('machine_predictions')
    op.drop_index(op.f('ix_anomaly_predictions_timestamp'), table_name='anomaly_predictions')
    op.drop_index(op.f('ix_anomaly_predictions_machine_id'), table_name='anomaly_predictions')
    op.drop_table('anomaly_predictions')
    op.drop_index(op.f('ix_production_batches_schedule_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_product_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_order_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_machine_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_batch_number'), table_name='production_batches')
    op.drop_table('production_batches')
    op.drop_index(op.f('ix_maintenance_records_machine_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_machine_readings_timestamp'), table_name='machine_readings')
    op.drop_index(op.f('ix_machine_readings_machine_id'), table_name='machine_readings')
    op.drop_table('machine_readings')
    op.drop_index(op.f('ix_machine_health_history_recorded_at'), table_name='machine_health_history')
    op.drop_index(op.f('ix_machine_health_history_machine_id'), table_name='machine_health_history')
    op.drop_table('machine_health_history')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_machine_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_schedule_revisions_schedule_id'), table_name='schedule_revisions')
    op.drop_table('schedule_revisions')
    op.drop_index(op.f('ix_production_orders_product_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_code'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_inventory_transactions_material_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_created_at'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_demand_forecasts_product_id'), table_name='demand_forecasts')
    op.drop_index(op.f('ix_demand_forecasts_forecast_date'), table_name='demand_forecasts')
    op.drop_table('demand_forecasts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_table('products')
    op.drop_table('production_schedules')
    op.drop_index(op.f('ix_production_lines_line_code'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_inventory_materials_material_code'), table_name='inventory_materials')
    op.drop_table('inventory_materials')
    # ### end Alembic commands ###
